### PR TITLE
When n_outputs is set, save only that many outputs from the simulation function

### PR DESCRIPTION
**Pull request by alec-hoyland**
* Made the `n_outputs` property writeable
* `simulate_core` only saves the first `n_outputs` outputs of the simulation function when `n_outputs` is non-NaN and non-empty.

### CODE REVIEW

**Comment by alec-hoyland** [comment]
This has been tested using `test_simple_sim` by setting `p.n_outputs = 1` before the `simulate` block.

**Comment by sg-s** [comment]
Hey @alec-hoyland can you re-open and resubmit this? I accidentally reverted it

**Comment by sg-s** [comment]
OK i made a huge mess. sorry.

**Comment by sg-s** [comment]
I think i iixed it -- pulled from your fork

**Pull request merged**
